---
title: Homework 6 - Getting started with python and mysql
date: 10/23/2023
author: Javeria Hanif
format:
    gfm:
        mermaid-format: png
---
## Homework Description

Homework 6 ... [add description]

## Professor Notes

This project kicks the course complexity up a notch. We're adding python and SQL to
spice up our cake mix with quarto as our tasty frosting.

### Homework tasks

Visit the Canvas homework site for more details:

1. Install the necessary python tools and libraries
2. Verify that the tools and libraries are installed.
3. Verify that you can log into the phpMyAdmin site.
4. Verify that your computer can connect to the mySql server.
5. Explore queries and result sets using pandas
6. Explore Quarto as a tool for writing out tables.
7. Explore and document a new database that some provided to you.

8. Render *explore.qmd* to ensure that everything works.
9. Complete the *hw6.qmd* scaffold and render the report

### Files and folders

All necessary files are stored in the *./hw6* folder.
